import { NgModule } from '@angular/core';
import { MatButtonModule,
         MatIconModule,
         MatFormFieldModule,
         MatInputModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatCheckboxModule,
         MatSidenavModule,
         MatToolbarModule,
         MatListModule,
         MatTabsModule,
         MatCardModule,
         MatSelectModule,
         MatProgressSpinnerModule,
         MatDialogModule,
         MatTableModule,
         MatPaginatorModule,
         MatSortModule,
         MatSnackBarModule,
         MatStepperModule,
         MatProgressBarModule
        } from '@angular/material';


@NgModule({

imports: [  MatButtonModule,
            MatIconModule,
            MatFormFieldModule,
            MatInputModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatCheckboxModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatTabsModule,
            MatCardModule,
            MatSelectModule,
            MatProgressSpinnerModule,
            MatDialogModule,
            MatTableModule,
            MatPaginatorModule,
            MatSortModule,
            MatSnackBarModule,
            MatStepperModule,
            MatDialogModule,
            MatProgressBarModule
        ],
exports: [  MatButtonModule,
            MatIconModule,
            MatFormFieldModule,
            MatInputModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatCheckboxModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatTabsModule,
            MatCardModule,
            MatSelectModule,
            MatProgressSpinnerModule,
            MatDialogModule,
            MatTableModule,
            MatPaginatorModule,
            MatSnackBarModule,
            MatSortModule,
            MatStepperModule,
            MatDialogModule,
            MatProgressBarModule]

})
export class MaterialModule {}
